# Generated by Django 5.2.7 on 2025-11-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('servicio', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
