# Generated by Django 5.2.7 on 2025-11-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cita_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('Limpieza Dental', 'Limpieza Dental'), ('Ortodoncia', 'Ortodoncia'), ('Blanqueamiento Dental', 'Blanqueamiento Dental'), ('Extracciones', 'Extracciones'), ('Implantes Dentales', 'Implantes Dentales'), ('Chequeo General', 'Chequeo General')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='telefono',
            field=models.FloatField(max_length=15),
        ),
    ]
